networks:
  mynetwork:
    driver: bridge

services:
  djangoapp:
    container_name: djangoapp
    build:
      context: .
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    volumes:
      - ./djangoapp:/djangoapp
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - psql
    command: /bin/sh -c "sleep 10 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  psql:
    container_name: psql
    image: postgres:13-alpine
    networks:
      - mynetwork
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - /dotenv_files/.env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}






      